### ISSUE TITLE
NECB 2015 Rules: Lighting loads

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#10]
Information in Table 4.2.1.5 and Table 4.2.1.6. for interior lighting power density for NECB 2015 is contained in an Excel file we received from NRC. In BTAP this information for lighting power density is held inside json files. Need to implement support for NECB 2015 lighting data.

Once the interior lighting information is in the database, the BTAP NECB2015 class will be modified as needed to link to the new interior lighting data.

Quality assurance tasks:
New unit tests for lighting controls
All unit tests pass
All regression tests pass

**Comment by phylroy** [comment]
This is linked to spacetype json mods.

**Comment by phylroy** [comment]
This was related to the spacetype task and has been updated in SpaceType JSON file.  So only data update was required.
