### ISSUE TITLE
NECB 2015 Tasks: HVAC equipment efficiencies

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#11]
Table 5.2.12.1 has information on equipment efficiencies. The information in this table needs to be reviewed to identify any needed changes in the efficiencies currently used in BTAP.

The efficiency information in BTAP is held inside several worksheets in json files for 'Boilers', 'Chillers', 'Heat Pumps', 'Heat Pumps Heating', and 'Unitary ACs'. Need to implement support for NECB 2015 equipment efficiency data in BTAP.

The BTAP NECB2015 class will be updated to link to the new NECB 2015 efficiency data.

Quality assurance rules:
New unit test for equipment efficiencies
All unit tests pass
All regression tests pass

**Comment by Shouldibuyacat** [comment]
Has this task been started? 

Where can I begin to help on this task.
If you can point me in the direction of the specific json worksheets that would be helpful.

Thank you.
