### ISSUE TITLE
Write method Remove duplicate materials, constructions from model

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#125]
When cloning or importing from a library a construction set.. it does a deep copy.. If you import more than one construction set.. It will create duplicates of materials and constructions. This causes a massive amount of bloat in the osm file. 

Currently this is not a problem since we are using one construction set for each arch building (mass walls) .. however, if we start applying the more than one construction set to a model, as we plan to with Mike's construction definitions that he created in the costing work.. this will balloon huge. 

This requires a bottom up approach.  The method should iterate through all the materials first in the model..  If duplicates are found. 
Stage 1 Materials
0. Iterate through all the materials and....
1. Determine the duplicates by comparing all properties (There may be a special idd or base Object method to help) 
2. Keep the one with the shortest name
3 Find all constructions using the material and replace it in the layer vector that we are keeping. 
4. Delete the other duplicates that are no longer used. 

Stage 2 Constructions
0. Iterate through all the constructions and....
1. Determine the duplicates by comparing all properties (There may be a special idd or base Object method to help) 
2. Keep the one with the shortest name
3 Find all constructions sets using the construction and replace it with the one that we are keeping. 
4. Delete the other duplicates that are no longer used. 

This may be challenging since this may require many different classes.. so it *may* require something innovative.  Perhaps comparing the idd base object in a similar way we have for the standards project osm regression tests, but for a single object and not a whole file.....,while ignoring the 'name' object field....

Here is a method that loads in the BTAP-Mass construction set into a model from an osm file.... (note this is on nrcan_44 branch which you may branch from and is hardcoded for now..but just to give you an idea.) 
https://github.com/NREL/openstudio-standards/blob/nrcan_44/lib/openstudio-standards/standards/necb/necb_2011/building_envelope.rb#L463

You can use/modify this method to see/test the duplication that entails and develop a solution.

**Comment by padmassun** [comment]
Merged
