### ISSUE TITLE
Adding space types to the shapes created from 'BTAPCreateGeometry' 

### ISSUE THREAD

**Issue by MarianaNRC** [canmet-energy/btap_tasks#132]
It is still not working, In the ruby script, it shows that 14 space-types were added, but these space-types don't appear in Open Studio,

**Comment by IainMacdonald** [comment]
This measure will re-set the space types in a model. Idea is that all spaces in the model will be assigned the same space type.
If anyone can think of a way to assign space types to a generic geometry then that could allow some flexibility - say by floor or orientation?

**Comment by IainMacdonald** [comment]
TO DO
Not required for NECB 2015 or NZER project. Move to 'feature request' project.
Iain and Mariana to discuss functionality

**Comment by IainMacdonald** [comment]
space types added to measure as past of task 129
