### ISSUE TITLE
NECB 2015 Rules: Cooling tower control

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#14]
According to this rule (8.4.4.12(6)) the only requirement now is to use cycling fan to maitain an outlet temperature of 29 DegC. The requirement for fan power will be based on information the new Table 5.2.12.2.

Quality assurance tasks:
New unit test.
All unit tests pass.
All regression tests pass

**Comment by phylroy** [comment]
@khaddad to close.
