### ISSUE TITLE
NECB 2011 and 2015 VAV with Reheat Supply Fan Power lower than NECB calculated value for many weather locations

### ISSUE THREAD

**Issue by ckirney** [canmet-energy/btap_tasks#146]
### Description
NECB 2011 and 2015 NECB VAV with Reheat supply fan is lower than what QAQC expected:

NECB 2011 (example):
[ERROR][TEST-FAIL][NECB2011-5.2.3.3]:[AIR LOOP][VAV with Reheat 1][:supply_fan][:rated_electric_power_w] [10418.05] Percent Diff from NECB value [15184.5] expected value:31.39 >= result value:10

NECB 2015 (example)
[ERROR][TEST-FAIL][NECB2015-5.2.3.3]:[AIR LOOP][VAV with Reheat 1][:supply_fan][:rated_electric_power_w] [1508.66] Percent Diff from NECB value [2199.5] expected value:31.409 >= result value:10

This was detected when testing the new OpenStudio Server 2.6.0.  OpenStudio Server 2.4.3 had issues that prevented the tests so I am not sure if the issue reported here is a problem in OpenStudio 2.4.3.

## 2011 Archetypes that failed for this test
The test failed for the following archetypes in all weather locations

2011 Archetype
-- |
MediumOffice
LargeOffice
LargeHotel
HighriseApartment
Hospital
Outpatient

## 2015 Archetypes that failed for this test
The test failed for the following archetypes in most of the weather locations (differences mentioned)

2015 Archetypes which failed in all weather locations:
-- |
Hospital
MediumOffice
Outpatient

2015 LargeOffice failed in all weather locations except:
-- |
Banff CS

2015 LargeHotel failed in all weather locations except:
-- |
Sept Illes AP

2015 HighriseApartment failed in all weather locations except:
-- |
Port Hardy AP
Brandon Muni AP
The Pas AP
Winnipeg-Richardson Intl AP
Gander Intl AP-CFB Gander
Goose Bay AP-CFB Goose Bay
St Johns Intl AP
Stephenville Intl AP
Charlottetown AP
Kuujjuaq AP
Kuujjuarapik AP
Lac Eon AP
Mont-Joli AP
Montreal-Mirabel Intl AP
Montreal-St-Hubert Longueuil AP
Montreal-Trudeau Intl AP
Quebec-Lesage Intl AP
Riviere-du-Loup
Roberval AP
Saguenay-Bagotville AP-CFB Bagotville
Schefferville AP
Sept-Iles AP
Val-d-Or Rgnl AP

## 2017 Archetypes that failed for this test
I didn't check NECB 2017 but it is worth a look if NECB 2017 can be tested.

### Approach
Review test, run sample tests locally, review code and figure out what is going on.

### Testing Plan
Probably use the existing tests.

### Waiting On
Someone's time.

### Repositories Involved
Probably just:
https://github.com/NREL/openstudio-standards/tree/nrcan

### Branch Name Created for this Task
None yet but whomever looks into this should change this if they feel it is warranted.

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by ckirney** [comment]
Pump power QAQC check added from NREL openstudio-standards issue # 219.  Also mentioned in NRCan btap-tasks issue #48.  Spot check using osm created via NECB 2015 Calgary Hospital revealed that pump power was determined normally.  Large deviations from theoretical may be a result of NECB 2015 rules as per btap-tasks issue #16.  OpenStudio also accounts for pump inefficiencies (not motor but the pump itself) with a 'Design Shaft Power per Unit Flow Rate per Unit Head' value that is defaulted to 1.282051282 (this is sometimes modified as per btap-tasks issue #16).

QAQC calculates theoretical pump power using:
hp_check = ((flow_rate*60*60)/1000*1000*9.81*pump_head*0.000101997)/3600000

where flow_rate is in L/s and pump_head is in Pa.  I am not sure what all of the constants are.  I will check with Mike later.

**Comment by phylroy** [comment]
@padmassun created this repository to run the files and produce the qaqc json file by invoking the btapresults measure.  A description on how to run the files are here. You will notice that there is a way to reduce the runs based on building type an location by modifing the code as described by him. 

https://github.com/canmet-energy/necb_archtypes_generator
