### ISSUE TITLE
Costing: Lighting

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#152]
### Description
Mike's lighting costing specification is applicable to NECB 2011, 2015 and 2017 Lighting compliant selections generated within BTAP and Open Studio.

### Approach
1.	Ensure that the NECB standard (i.e., 2011, 2015 or 2017) is set for each archetype so that it can be matched to the data in the “lighting_sets” sheet
2.	Read “spaces” (within zones) to get the space function type
3.	Search “lighting_sets” Column B for Space Function and then Column C for space function
4.	Using average height, determine which fixture type is required (column G, H or I from “lighting_sets” sheet) for the space type
5.	Go to “lighting” sheet and read Column A to find the matching fixture type row
6.	On “lighting” sheet read column E, G, I and on “materials_sheet” column F corresponding to values in Column G
7.	This gives you the data for the API call:
        -	Catalog id
        -	Materials id
8.	Return MaterialOPCost and LabourOPCost for each item in “lighting” column G
9.  Multiply each returned value by corresponding multiplier (Column I) to determine national average cost/ft2
10.	Read space type “volume”: and divide by average height to determine space floor area in ft2
11.	Multiply each returned value by ft2 and the .json “multiplier” for the space type to get a component material cost and labour cost (both including overhead and profit)
12.	Sum materials and labour to get a space lighting material cost and a space lighting labour cost (both including OP)
13.	Repeat 2-12 for next space
14.	When completed all of the spaces, sum lighting material costs and lighting labour costs to obtain national average total lighting material and total lighting labour costs (both including OP)
15.	Apply “rsmeans_local_factors” sheet values for Column C (division = ELECTRICAL, COMMUNICATIONS, & UTIL.) for the material (Column E) to national average material and installation (Column F) to national average labour for the city (Column B) matching the closest weather “city”:  and the corresponding costing city (sheet RegionalMap).  It is assumed that lighting costing (material, labour) all fall under division = ELECTRICAL, COMMUNICATIONS, & UTIL.  and other trades that may be involved (ex. drywalling of light switches) use the same local factors. 

### Testing Plan
Test FullServiceRestaurant, LargeOffice and LargeHotel for NECB 2011,2015 and 2017

### Waiting On
Nothing. 

### Repositories Involved

https://github.com/canmet-energy/btap_costing.git

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by mlubun** [comment]
Lighting specification added for 2011, 2015, 2017
Lighting .xls data file added
[BTAP-Lighting Costing Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2394655/BTAP-Lighting.Costing.Spec.docx)
[national_average_cost_information.xlsx](https://github.com/canmet-energy/btap_tasks/files/2394661/national_average_cost_information.xlsx)

**Comment by mlubun** [comment]
made a mistake, did not realize I was closing the issue when I thought I was closing the comment

**Comment by jblake59** [comment]
Lighting cost coding complete and done initial comparisons with Mike's hand/sheet calculations. All archetypes run through successfully for NECB2011 but haven't verified calcs for anything but FullServiceRestaurant.  

NECB2015 only runs when disable qaqc code. This needs to be fixed.

NECB2017 data missing from national_average_cost_information.xlsm. @mlubun needs to add.

**Comment by jblake59** [comment]
This issue can be closed once reviewed by @phylroy.

**Comment by phylroy** [comment]
TO confirm Necb2015 matches Mikes hand calc.

**Comment by jblake59** [comment]
2015 LargeHotel matches!
Mike's Calcs: $504,647.43
cost_results: $504,830.83

Note that 2011 LargeHotel does not:
Mike's Calcs: $704,427.00
cost_results: $690,782.28
The difference is in Mech_Flr_1

**Comment by mlubun** [comment]
Excellent Jeff,  I fixed my hand calc (did not apply the right multipliers when I changed fixture types in the mech room)  so my hand calc more closely matches your coding

2011 LargeHotel
costs_results: $690,782.28
Mike's Calcs: $691,887.21

[lighting costing example.xlsx](https://github.com/canmet-energy/btap_tasks/files/2611758/lighting.costing.example.xlsx)

**Comment by jblake59** [comment]
Schedule a code walk-through with Phyroy, Chris and Mike before closing this issue.
