### ISSUE TITLE
Number of Stories Calculation Likely Excluding Multipliers

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#158]
Multi-storey bldgs. # floors is used for costing, but the number of floors in the .json does not match the drawings.  See .json below

"os_standards_revision": "8988a1a",
  "os_standards_version": "0.2.2",
  "openstudio_version": "2.4.3.29a61f6637",
  "energyplus_version": "8.9.0",
  "date": "2018-08-07 12:53:42 +0000",
  "building": {
    "name": "-MidriseApartment-NECB HDD Method-CAN_AB_Fort.McMurray.AP.716890_CWEC2016.epw created: 2018-08-07 12:49:40 +0000",
    "conditioned_floor_area_m2": 3134.614198677911,
    "exterior_area_m2": 2325.693387747441,
    "volume": 9553.837020054672,
    "number_of_stories": 3
  },

The midrise is 4 stories.  Thermal zoning: Gr with a multiplier of 1, Mid with a multiplier of 2 and Top with a multiplier of 1.  If the multiplier is included, the correct number of stories is produced (assuming the multiplier is a floor multiplier)

Same issue with the large office:
"os_standards_revision": "8988a1a",
  "os_standards_version": "0.2.2",
  "openstudio_version": "2.4.3.29a61f6637",
  "energyplus_version": "8.9.0",
  "date": "2018-08-07 12:50:40 +0000",
  "building": {
    "name": "-LargeOffice-NECB HDD Method-CAN_AB_Edmonton.Intl.AP.711230_CWEC2016.epw created: 2018-08-07 12:47:09 +0000",
    "conditioned_floor_area_m2": 46320.37831616,
    "exterior_area_m2": 15152.641055360002,
    "volume": 178146.03714033676,
    "number_of_stories": 4
  },

The large office is 12 stories above grade and a basement storey.  Thermal zoning: "Basement" with a multiplier of 1,  "Core_bottom" with a multiplier of 1, "Core_mid" with a multiplier of 10, "Core_Top" with a multiplier of 1.  There is also the plenum which may be included or not (likely not), as the Basement seems to be counted as a storey.  If the multipliers are included, then you have 13 stories including the basement.

The small hotel is 4 stories, but each storey is modelled meaning multiplier = 1.  The .json correctly reports the number of stories:
"os_standards_revision": "8988a1a",
  "os_standards_version": "0.2.2",
  "openstudio_version": "2.4.3.29a61f6637",
  "energyplus_version": "8.9.0",
  "date": "2018-08-07 12:59:59 +0000",
  "building": {
    "name": "-SmallHotel-NECB HDD Method-CAN_AB_Edmonton.Stony.Plain.AP.711270_CWEC2016.epw created: 2018-08-07 12:47:45 +0000",
    "conditioned_floor_area_m2": 4013.5822124453694,
    "exterior_area_m2": 2697.9740592115513,
    "volume": 11621.728654360992,
    "number_of_stories": 4

Solution: Check to see if multipliers are included in number of stories calculation.  The multiplier method will not work for some archetypes as large hotel has a multiplier of 76 for some thermal zones.  The large hotel is 6 stories, plus a basement
 "os_standards_revision": "8988a1a",
  "os_standards_version": "0.2.2",
  "openstudio_version": "2.4.3.29a61f6637",
  "energyplus_version": "8.9.0",
  "date": "2018-08-07 12:56:29 +0000",
  "building": {
    "name": "-LargeHotel-NECB HDD Method-CAN_AB_Edmonton.Intl.AP.711230_CWEC2016.epw created: 2018-08-07 12:47:25 +0000",
    "conditioned_floor_area_m2": 11345.286931,
    "exterior_area_m2": 6004.666986399999,
    "volume": 35184.76930266,
    "number_of_stories": 4

**Comment by phylroy** [comment]
Hi Mike, 

the number of stories that you are seeing is the computed value.. However there is a user entered field that we have access to that is the number of floors interpreted by the modeller. Would you like us to make that available to you in the json file?

**Comment by phylroy** [comment]
created a branch NRCan_158 and made modifications there to add the above information to the json file.. This will need to be merged into NRCan branch if deemed okay.  Please review to see changes. 
https://github.com/NREL/openstudio-standards/commit/3a48444609189860d7e96e03a2b28b57d1ade7c6
