### ISSUE TITLE
NECB 2015 Rules: Pumping power demand

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#16]
Table 5.2.6.3. contains information on peak pumping power demand. After the sizing run, the peak thermal load on the loop needs to be determined. Then the pump parameters need to be set according to the information in the previous table.

Quality assurance rules:
New unit test
All unit tests pass
All regression tests pass

**Comment by jblake59** [comment]
I'm trying to figure this out! @Kamel: It would be handy to have the 2015 code text around this table.

**Comment by jblake59** [comment]
![image001](https://user-images.githubusercontent.com/6492248/37991279-c59a3956-31d6-11e8-8a8e-9064562771a7.png)

**Comment by ckirney** [comment]
This task is complete and is awaiting code review and acceptance of the pull request from nrcan_16 into nrcan.  The unit test portion of this task is now being tracked separately under issue #66.
