### ISSUE TITLE
NECB2015:  Change HVAC system Selection Type for "laundry/Washing area" from "Assembly Area" to "Hospital Area"

### ISSUE THREAD

**Issue by ckirney** [canmet-energy/btap_tasks#160]
### Description
In NECB 2011 the "Laundry/Washing area" space type was listed as "Hospital - laundry/washing".  In NECB 2015 and thereafter "Laundry/Washing area" became its own space type independent of hospital.  Thus, in NECB 2011 the "Hospital - laundry/washing area" space type fell under the "Hospital Area" HVAC system selection type (because of the hospital prefix) and was thus the HVAC system was set as type 3.  However, in NECB 2015 and thereafter "Laundry/Washing area" was no longer under the hospital umbrella so fell into the "Assembly Area" HVAC system selection type.  This meant that, depending on the number of storeys in the building, the HVAC system could be type 3 (for up to 4 storeys) or type 6 (for more than 4 storeys).  Thus, for the LargeHotel archetype (with more than 4 storyes) the system type for the laundry rooms switched from type 3 in NECB 2011 to type 6 in NECB 2015 and NECB 2017.

Table 8.4.4.7.-A in NECB 2011, NECB 2015, or NECB 2017 never specifically includes "Laundry/Washing area" or mentions either "laundry" or "washing" under its "Building or Space Type of the Proposed Building" column.  Thus the code stays silent on which HVAC system type it should be.  Mike Lubun believes that, because of the high humidity in these types of spaces, it should fall under HVAC system type 3.  Since code remains silent, the "necb_hvac_system_selection_type" field for the "Laundry/Washing area" space type in the NECB 2015 space_types.json file will be changed from "Assembly Area" to "Hospital Area".

### Approach
Change the "necb_hvac_system_selection_type" field for the "Laundry/Washing area" space type in the NECB 2015 space_types.json file from "Assembly Area" to "Hospital Area".

### Testing Plan
Existing tests will be run and expected files modified to reflect the change in expected results.

### Waiting On
Nothing.

### Repositories Involved

https://github.com/NREL/openstudio-standards/tree/nrcan

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by phylroy** [comment]
@ckirney to
