### ISSUE TITLE
Ventilation Costing (step 6 after issue #156): Determine Cost of Ventilation Air Distribution System

### ISSUE THREAD

**Issue by ckirney** [canmet-energy/btap_tasks#167]
### Description
Determine the cost of the ventilation air distribution system.

### Approach
See the attached specification.
[Ventilation.Distribution.Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2550362/Ventilation.Distribution.Spec.docx)

### Testing Plan
Create a new test for determining the distribution system and ducting lengths. Create a separate test (maybe) of the costing information using dummy RSMeans data.

### Waiting On
Someone's time.

### Repositories Involved

https://github.com/canmet-energy/btap
https://github.com/NREL/openstudio-standards/tree/nrcan (Maybe)

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by ckirney** [comment]
Updated specification based on Mike's revised spec.

**Comment by ckirney** [comment]
Finished the get_story_cent_to_edge method.  This determines the centroid of a ceiling perimeter line, point A, on the provided building story which is furthest from a supplied point, point O.  Also provides where line AO intercepts the building story ceiling perimeter on the other side of the building.

See below for comments describing this method from the file:

This method finds the centroid of the ceiling line on a given story furthest from the specified point.  It only takes into account ceilings that above conditioned spaces that are not plenums.  A line can be defined between the supplied point (we'll call it point O) and the ceiling line centroid furthest from that point(we'll call it point A).  We will call this line AO.  If the full_length input argument is set to true the method will also return the point where line AO intercepts the ceiling line on the other side of the building.  Note that the method only looks at x and y coordinates and ignores the z coordinate of the point you pass it.  The method assumes that the ceilings of all of the spaces on the floor you pass it are flat so generally ignores their z components as well.  This was done to avoid further complicating things with 3D geometry.  If the ceilings of all of the spaces in the building story you pass the method are not flat it will still work but pretend as though the ceilings are flat by ignoring the z coordinate.
 
The method works by going through each space in the supplied building story and finding the ones which are conditioned (either heated or cooled) and which are not considered plenums.  It then goes through the surfaces of the conditioned spaces and finds the ones which have an OpenStudio SurfaceType of 'RoofCeiling'.  It then goes through each point on that surface and makes lines going from the current point (CP) to the previous point (PP).  It calculates the centroid (LC) of the line formed between PP and CP by averaging each coordinate of PP and CP.  It then determines which LC is furthest from the supplied point (point O) and this becomes point A.  Note that point A is not necessarily on the outside of a building since no checks are made on where line P lies in the building (only that it is on a RoofCeiling above a conditioned space that is not a plenum).  For example in the LargeOffice building archetype point P generally lies on one of the short edges of the trapezoids forming the perimeter spaces.  This is if this reference point (O) is the center of the building.

The inputs arguments are are:
building_story:  OpenStudio BuildingStory object.  A building story defined in OpenStudio.
prototype_creator:  The Openstudio-standards object, containing all of the methods etc. in the nrcan branch of Openstudio-standards.
target_cent:  Array.  The point you supply from which you want to find the furthest ceiling line centroid (point O in the description above).  This point should be a one dimensional array containing at least two elements target_cent[0] = x, target_cent[1] = y.  The array can have more points but they will be ignored.  This point should be inside the building.
tol:  Float.  The tolerence used by the method when rounding geometry (default is 8 digits after decimal).
full_length:  Boolean true/false The switch which tells the method whether or not it should find, and supply, the point where line AO (as defined above) intercepts the other side of the building.  It is defaulted to false, meaning it will only return points A and O.  If it set to 'true' it will return the point where line AO intercepts the other side of the building.  It does this by going through all of the ceiling lines in the specified building story and determining if any intercept line AO (let us call each intercepts point C).  It then runs through each intercept (point C) and determines which C makes line AOC the longest.

The output is the following hash.

{
   start_point:  Hash.  A hash which defines point A and provides a bunch of other information (see below),
   mid_point:  Hash.  This is a hash containing the array defining the point you passed the method in the first place.,
   end_point:  Hash.  If full_length was set to true then this defines point C and provides a bunch of other information (see below).  If full_length was not set to false or undefined then this is set to nil.

The structure of the hashes start_point and end_point are identical.  I will only define the hash start_point below noting differences for end_point.

start_point: {
   space:  OpenStudio Space object.  The space that contains point A (or point C if in the end_point hash).,
   surface:  OpenStudio Surface object.  The surface in space that contains point A (should have a RoofCeiling SpaceType).  In the case of the end_point hash this is the surface that contains point C.,
  verts:  Two dimmensional array.  The points defining ':surface'.  These points are in the building coordinate system (rather than the space coordinate system).  These points are ordered clockwise when viewed with the surface normal pointed towards the viewer.  The array would be structured as follows: [1st point, 2nd point, ..., last point].  Each point is an array as follows:  [x coord, y coord, z coord].  The points are in meters.,
   line:  Hash.  A hash defining the line containing point A (point C if this is in the 'end_point' hash).  See definition below.
}

'line' has the identical structure in the start_point and end_point hashes.  I will define it once but note any differences for when it is containing in the start_point and end_point hashes.

line: {
   verta:  Array.  The end point of the line containing point A (when in the start_point hash) or point C (when in the end_point hash).  It is formed as [x, y, z].  It is in the building coordinate system, in meters.
   ventb:  Array.  The start point of the line containing point A (when in the start_point hash) or point C (when in the end_point hash).  It is formed as [x, y, z].  It is in the building coordinate system, in meters.
   int:  Array.  If this is in the start_point hash then this is the centre of the line from vertb to verta.  If this is in the end_point hash then this is the intercept of the line AO with the line starting with vertb and ending with verta.  It is formed as [x, y, z].  It is in the building coordinate system, in meters.  If in the start_point hash then the z coordinate is the average of the z coordinates of verta and vertb.  If in the end_point hash then the z coordinate is calculated by first determining of the distance of the line between vertb and verta when only using their x and y coordinates (we will call it the xy_dist).  Then the distance from just the x and y coordinates of ventb to the x and y coordinates (the only ones provided) of point C is determined (we will call it the c_dist).  The fraction c_dist/xy_dist is then found and added to the z coordinate of ventb thus providing the z coordinate of point C.
   i:    Integer.  The index of verta in the verts array.
   ip:   Integer.  The index of vertb in the verts array.
   dist:  If in the start_point hash this is the distance between point A and point O using only the x and y coordinates of the respective points.  If in the end_point hash this is the distance between point A and point C using only the x and y coordinates of the respective points.  In meters.
}

**Comment by phylroy** [comment]
I dont understand what you mean issue #157

**Comment by ckirney** [comment]
Ventilation distribution costing completed.
