### ISSUE TITLE
Ventilation Costing (6) Adding the Distribution System 

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#172]
[Ventilation Distribution Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2535703/Ventilation.Distribution.Spec.docx)

**Comment by ckirney** [comment]
This task is a duplicate of task #167 with an revised ventilation distribution specification.  I have updated the ventilation distribution specification in task #167 and am closing this task to avoid confusion.
