### ISSUE TITLE
Ventilation Costing (8) Adding HRV and Ducting

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#174]
[HRV Cost and Ducting Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2535722/HRV.Cost.and.Ducting.Spec.docx)

**Comment by ckirney** [comment]
See attached for revised costing specification.
[HRV.Cost.and.Ducting.Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2894174/HRV.Cost.and.Ducting.Spec.docx)
