### ISSUE TITLE
Duplicate space types

### ISSUE THREAD

**Issue by ckirney** [canmet-energy/btap_tasks#181]
### Description
In some necb 2015 and 2017 regression test files, space types are duplicated.  For example, the 2017 regression test for LargeHotel (either fuel type) has the following two space types:

Space Function Storage room < 5 m2-sch-A
Space Function Storage room < 5 m2-schA 1

Likewise there are duplicate default loads associated with these two space types:

Space Function Storage room < 5 m2-sch-A People
Space Function Storage room < 5 m2-sch-A Lights
Space Function Storage room < 5 m2-sch-A Elec Equip

and

Space Function Storage room < 5 m2-sch-A 1 People
Space Function Storage room < 5 m2-sch-A 1 Lights
Space Function Storage room < 5 m2-sch-A 1 Elec Equip

Everything about the two space types are identical (including the loads).  I am not sure why this is but it causes problems when trying to look up a space type in the data table.

### Approach
Requires further investigation.

### Testing Plan
Existing tests should work.

### Waiting On
Someone's time.

### Repositories Involved

https://github.com/NREL/openstudio-standards/tree/nrcan

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by phylroy** [comment]
This due to the updates that Edward has done to scheduling.  So there may be duplicates created in 2015/17.  This is expected since there may be some zones that are modified and some that are not.  So the old spacetype needs to be around for the unmodified spaces.
