### ISSUE TITLE
Space Heating: Boiler Costing

### ISSUE THREAD

**Issue by jblake59** [canmet-energy/btap_tasks#182]
### Description
Code the costing of heating system boilers for the NECB 2011 standard.

### Approach
From Mike's (@mlubun) spec:
1. 	Determine the type of heating systems in the building
2. 	Locate the Boiler, Heating Equipment in the Zone or in a Mech Room
3.	Determine Boiler/Pumps costs

### Testing Plan
Test selected archetypes under NECB 2011 for errors. Compare results against hand calculations done by Mike.

### Waiting On
Nothing.

### Repositories Involved

https://github.com/canmet-energy/btap_costing

### Project Code to be charging in 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by mlubun** [comment]
Modified boiler spec to include back-up boiler and conduit for electrical services to all boilers
[BTAP-Boiler Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2681493/BTAP-Boiler.Spec.docx)

**Comment by mlubun** [comment]
Boiler and pump test .xls  (see sheet 2011largeoffice-boiler+pumps)

[lighting costing example.xlsx](https://github.com/canmet-energy/btap_tasks/files/2681495/lighting.costing.example.xlsx)

[CAN_BC_Prince.George.Intl.AP.718960_CWEC2016largeoffice.zip](https://github.com/canmet-energy/btap_tasks/files/2681510/CAN_BC_Prince.George.Intl.AP.718960_CWEC2016largeoffice.zip)

**Comment by mlubun** [comment]
Use the secondary school fro prince george as the office example has errors
[lighting costing example.xlsx](https://github.com/canmet-energy/btap_tasks/files/2681698/lighting.costing.example.xlsx)

[CAN_BC_Prince.George.Intl.AP.718960_CWEC2016sec.zip](https://github.com/canmet-energy/btap_tasks/files/2681703/CAN_BC_Prince.George.Intl.AP.718960_CWEC2016sec.zip)

**Comment by jblake59** [comment]
This work is complete.
