### ISSUE TITLE
Pump Costing Spec

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#186]
Pump and water piping for boilers, chillers (evaporator and condenser/cooling towers), SHW and DHW.

**Comment by mlubun** [comment]
Spec for pump costing completed.  The pump costing is virtually identical for boilers, chillers, condensers and service water heaters, so they have been combined into 1 spec
[BTAP-Pump Costing Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2673198/BTAP-Pump.Costing.Spec.docx)

**Comment by mlubun** [comment]
[BTAP-Pump Costing Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2704296/BTAP-Pump.Costing.Spec.docx)

updated pump costing to include variable speed pumps and costing procedures for VFD controllers

**Comment by jblake59** [comment]
Completed for boilers and committed (and merged with master).

**Comment by jblake59** [comment]
Complete for boilers, chillers and cooling tower (condenser) pumps.
