### ISSUE TITLE
Space Cooling: Cooling Tower Costing Spec

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#188]
In progress

**Comment by mlubun** [comment]
spec attached
[BTAP-CoolingTower Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2725371/BTAP-CoolingTower.Spec.docx)

**Comment by mlubun** [comment]
[BTAP-CoolingTower Spec 2.docx](https://github.com/canmet-energy/btap_tasks/files/2728766/BTAP-CoolingTower.Spec.2.docx)

**Comment by jblake59** [comment]
Complete.
