### ISSUE TITLE
PAT: quantify changes to energy resulting from new FDWR in PCF-zxy

### ISSUE THREAD

**Issue by IainMacdonald** [canmet-energy/btap_tasks#208]
### Description
PAT model using 2017 archetypes as baseline to evaluate effect of new FDWR and skylight allowance as described in PCF-zxy.

### Approach
Using 2017 archetypes apply new rules.

Requires measures to change FDWR rule (% by degree days) and skylights. The PCF removes the 2% allowance for skylights.

Costing not required.

### Waiting On
May have to write new measures (see task 1)

### Steps
1) Edward to upload PCF - **done**
2) Edward to check is measures exist to run this study  **done**
3) If measures required - do it! Iain to update timeline and inform ctte.  **done**
4) Edward to build PAT model and run simulations  **done**

### Timelines
TG-BE want results for Jan 29th meeting. If new measures required this will be hard to achieve.

**Comment by edwardv720** [comment]
[FDWR + skylight PCF.docx](https://github.com/canmet-energy/btap_tasks/files/2769449/FDWR.%2B.skylight.PCF.docx)

**Comment by edwardv720** [comment]
PAT project - https://github.com/edwardv720/btap/tree/nrc_208/pat_projects/FDWR%2Bskylight-remov

Draft report presented at TG-BE.
