### ISSUE TITLE
Include component cost details in btap_results output.json

### ISSUE THREAD

**Issue by ckirney** [canmet-energy/btap_tasks#223]
### Description
Create a table in the costing output of btap_results that includes details of each HVAC component that was costed. This output should only be available for internal use so a switch will have to be added to turn it on or off depending on who we are doing a run for. The output should be a hash that looks like:

"hvac_costing_summary": [
       {  material:  Gasline,
          description: "Gas Line tubing with lightning protection 3/4",
          size:  ' ',
          unit:  "L.F",
          id:  "231123200140"
          cost_per_unit:  xxx.xx,,
          number_of_units:  xxx.xx,
          total_cost:  xxxxx.xx
       },
       {  material:  ElecBoilers,
          description: "Boiler, electric, hot water, 370 KW, 1263 MBH, ASME, includes standard controls and 
                               trim",
          size:  370,
          unit:  "each",
          id:  "235213102280"
          cost_per_unit:  xxx.xx,,
          number_of_units:  xxx.xx,
          total_cost:  xxxxx.xx
       }
]      

### Approach

Create the hash described above (similar to one that was created for constructions)  Every time a component needs costing search the hash and look for it.  If it is there continue as normal.  If not, add it to the hash.  Include this hash in the output hash for inclusion in qaqc.json and, ultimately, simualtions.json.

### Testing Plan
Check that qaqc.json contains the appropriate information.

### Waiting On
Someone's time. 

### Repositories Involved

https://github.com/canmet-energy/btap_costing

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by ckirney** [comment]
We should include something for assemblies which would include costing for individual components but also include any fudge factors that happens to account for things such as components which do not exist (for example non-standard insulation thicknesses).

**Comment by ckirney** [comment]
Proposed assembly cost structure:
{Assembly_name: BTAP-ExteriorRoof-IEAD-4,
Climate_zone: "Zone 5",
resistance_rsi_k_m2_per_w: 5.46
Description: "Deck Roof with a Membrane on a Steel Deck",
material_opaque_id_layers: [94, 88, 91, 100, 93]
Code: "NECB_2011",
Multipiler: xxxx.xx
Assembly: [
{ material_opaque_id: 88,
description: "plywood underlayments 0.5" thick",
quantity: 1,
unit: "ft2",
id: "061626100105",
material_mult: 1,
labour_mult: 1,
op_mult: 0.225,
cost_per_unit: xxx.xx,,
number_of_units: xxx.xx,
total_cost: xxxxx.xx
},
{ material_opaque_id: 94,
description: "60 ml Single ply EPDM .......",
quantity: 0.01,
unit: "SQ.",
id: "075323204800",
material_mult: 1,
labour_mult: 1,
op_mult: 0.29,
cost_per_unit: xxx.xx,,
number_of_units: xxx.xx,
total_cost: xxxxx.xx
}
....
]
}

**Comment by phylroy** [comment]
@ckirney I like the structure above..... but perhaps we could move the materials to a separate JSON table? Otherwise we risk duplicating data? Also.. if we do post-processing cost data with user cost data the data manipulation would be easier as well.

**Comment by ckirney** [comment]
I think it will not be so simple, especially with hvac data.  I will have to think about it some more.
