### ISSUE TITLE
Zone Cooling Devices (window AC, mini-splits)

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#226]
See attached spec.  Combo heating/cooling zone devices such as heat pumps and fan coils have been covered in the zone heating device spec
[BTAP-Zone Cooling Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2988235/BTAP-Zone.Cooling.Spec.docx)

**Comment by phylroy** [comment]
@jblake59 check status and dicuss with Mike for next meeting.

**Comment by jblake59** [comment]
The coding has been done for this but not tested against a file that contains these systems.
