### ISSUE TITLE
Merging nrel 2.8.0

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#227]
### Description
As title suggests

**Comment by phylroy** [comment]
Here is a list of the files that are in conflict.. I will attempt to log all changeds to each file when necessary. 
.circleci/config.yml
data/standards/OpenStudio_Standards.xlsx
data/standards/OpenStudio_Standards_construction_properties.json
data/standards/OpenStudio_Standards_construction_sets.json
data/standards/OpenStudio_Standards_economizers.json
data/standards/OpenStudio_Standards_heat_pumps.json
data/standards/OpenStudio_Standards_heat_pumps_heating.json
data/standards/OpenStudio_Standards_space_types.json
lib/openstudio-standards.rb
lib/openstudio-standards/prototypes/cbes/cbes.Model.elevators.rb
lib/openstudio-standards/prototypes/common/objects/Prototype.Model.elevators.rb
lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb
lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb
lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb
lib/openstudio-standards/prototypes/common/prototype_metaprogramming.rb
lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
lib/openstudio-standards/standards/Standards.ChillerElectricEIR.rb
lib/openstudio-standards/standards/Standards.Model.rb
lib/openstudio-standards/standards/Standards.SpaceType.rb
lib/openstudio-standards/standards/cbes/cbes.Space.rb
lib/openstudio-standards/standards/cbes/cbes_t24_2005/cbes_t24_2005.Space.rb
lib/openstudio-standards/standards/cbes/cbes_t24_2008/cbes_t24_2008.Space.rb
lib/openstudio-standards/standards/necb/NECB2011/building_envelope.rb
lib/openstudio-standards/standards/necb/NECB2011/data/space_types.json
lib/openstudio-standards/standards/necb/necb_2011/service_water_heating.rb
lib/openstudio-standards/version.rb
openstudio-standards.gemspec
test/90_1_prm/test_create_performance_rating_method_baseline_bldg_2.rb
test/90_1_prm/test_create_performance_rating_method_baseline_bldg_3.rb
test/90_1_prm/test_create_performance_rating_method_baseline_building.rb
test/circleci_tests.txt
test/doe_prototype/test_add_hvac_systems.rb
test/doe_prototype/test_full_service_restaurant.rb
test/doe_prototype/test_high_rise_apartment.rb
test/doe_prototype/test_hospital.rb
test/doe_prototype/test_large_hotel.rb
test/doe_prototype/test_large_office.rb
test/doe_prototype/test_medium_office.rb
test/doe_prototype/test_mid_rise_apartment.rb
test/doe_prototype/test_outpatient.rb
test/doe_prototype/test_primary_school.rb
test/doe_prototype/test_quick_service_restaurant.rb
test/doe_prototype/test_retail_standalone.rb
test/doe_prototype/test_secondary_school.rb
test/doe_prototype/test_small_hotel.rb
test/doe_prototype/test_small_office.rb
test/doe_prototype/test_strip_mall.rb
test/doe_prototype/test_supermarket.rb
test/doe_prototype/test_warehouse.rb
test/helpers/create_doe_prototype_helper.rb

**Comment by phylroy** [comment]
All items in the data/standards folder are no longer used by nrcan.  So will default to master for all changes there. 

data/standards/OpenStudio_Standards.xlsx
data/standards/OpenStudio_Standards_construction_properties.json
data/standards/OpenStudio_Standards_construction_sets.json
data/standards/OpenStudio_Standards_economizers.json
data/standards/OpenStudio_Standards_heat_pumps.json
data/standards/OpenStudio_Standards_heat_pumps_heating.json
data/standards/OpenStudio_Standards_space_types.json

**Comment by phylroy** [comment]
.circleci/config.yml
Two changes occurred on NRCan branch. 
1) nrcan locked the version of openstudio to 2.6.0 for circle ci
2) Padmassun added the following run commands. These are being revert to NRELs test format for the time being. 
```
      - run:
          name: Generate test files
          command: |
            bundle exec rake test:gen-circ-files
```
      - run:
          name: Copy test result Timings
          command: |
            cp -R test/reports timing/
```

```

**Comment by phylroy** [comment]
lib/openstudio-standards.rb

1) NREL requires open3 gem
2) NREL Changes to CBES and added methods get_run_env and run_command
3) NRCan changed/added paths for NECB work.

**Comment by phylroy** [comment]
lib/openstudio-standards/prototypes/cbes/cbes.Model.elevators.rb
Accept NRELs copy

**Comment by phylroy** [comment]
lib/openstudio-standards/prototypes/common/objects/Prototype.Model.elevators.rb
We renamed the method to get information from the 'standards json to standards_lookup_table_first' from model_find_object.  However NREL is using a complete new way to get information for elevators. So accepting NREL copy.

**Comment by phylroy** [comment]
lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb
change 
changed
model_find_object()
standards_lookup_table_first(table_name: 'whatever', search_criteria: search_criteria)

**Comment by phylroy** [comment]
A good chunk of SWH was removed by NREL... To preserve this.. it was moved to service_hot_water_heating.rb in the NECB2011 class.

**Comment by phylroy** [comment]
lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb

replaced model_lookup with 
standards_lookup_table_first(table_name: 'walkin_refrigeration', search_criteria: search_criteria)

**Comment by phylroy** [comment]
lib/openstudio-standards/prototypes/common/prototype_metaprogramming.rb

automerged

**Comment by phylroy** [comment]
lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
resolved with 
standards_lookup_table_first(table_name: 'economizers', search_criteria: search_criteria)

**Comment by phylroy** [comment]
lib/openstudio-standards/standards/Standards.ChillerElectricEIR.rb
standards_lookup_table_first(table_name: 'chillers', search_criteria: search_criteria, capacity: capacity_tons, date: Date.today)

**Comment by phylroy** [comment]
lib/openstudio-standards/standards/Standards.Model.rb
replaced def of 
  model_object_find()
with 
   standards_lookup_table_first()

also the method def model_add_prm_construction_set(model, category was removed

here is the code that was removed
``` ruby
# Creates a construction set with the construction types specified in the
  # Performance Rating Method (aka Appendix G aka LEED) and adds it to the model.
  # This method creates and adds the constructions and their materials as well.
  #
  # @param category [String] the construction set category desired.
  # Valid choices are Nonresidential, Residential, and Semiheated
  # @return [OpenStudio::Model::DefaultConstructionSet] returns a default
  # construction set populated with the specified constructions.
  def model_add_prm_construction_set(model, category)
    construction_set = OpenStudio::Model::OptionalDefaultConstructionSet.new

    # Find the climate zone set that this climate zone falls into
    climate_zone_set = model_find_climate_zone_set(model, clim)
    unless climate_zone_set
      return construction_set
    end

    # Get the object data
    data = model_find_object(standards_data['construction_sets'], 'template' => template, 'climate_zone_set' => climate_zone_set, 'building_type' => building_type, 'space_type' => spc_type, 'is_residential' => is_residential)
    unless data
      data = model_find_object(standards_data['construction_sets'], 'template' => template, 'climate_zone_set' => climate_zone_set, 'building_type' => building_type, 'space_type' => spc_type)
      unless data
        return construction_set
      end
    end

    OpenStudio.logFree(OpenStudio::Info, 'openstudio.standards.Model', "Adding construction set: #{template}-#{clim}-#{building_type}-#{spc_type}-is_residential#{is_residential}")

    name = model_make_name(model, clim, building_type, spc_type)

    # Create a new construction set and name it
    construction_set = OpenStudio::Model::DefaultConstructionSet.new(model)
    construction_set.setName(name)

    # Specify the types of constructions
    # Exterior surfaces constructions
    exterior_floor_standards_construction_type = 'SteelFramed'
    exterior_wall_standards_construction_type = 'SteelFramed'
    exterior_roof_standards_construction_type = 'IEAD'

    # Ground contact surfaces constructions
    ground_contact_floor_standards_construction_type = 'Unheated'
    ground_contact_wall_standards_construction_type = 'Mass'

    # Exterior sub surfaces constructions
    exterior_fixed_window_standards_construction_type = 'IEAD'
    exterior_operable_window_standards_construction_type = 'IEAD'
    exterior_door_standards_construction_type = 'IEAD'
    exterior_overhead_door_standards_construction_type = 'IEAD'
    exterior_skylight_standards_construction_type = 'IEAD'

    # Exterior surfaces constructions
    exterior_surfaces = OpenStudio::Model::DefaultSurfaceConstructions.new(model)
    construction_set.setDefaultExteriorSurfaceConstructions(exterior_surfaces)
    exterior_surfaces.setFloorConstruction(model_find_and_add_construction(model,
                                                                           climate_zone_set,
                                                                           'ExteriorFloor',
                                                                           exterior_floor_standards_construction_type,
                                                                           category))

    exterior_surfaces.setWallConstruction(model_find_and_add_construction(model,
                                                                          climate_zone_set,
                                                                          'ExteriorWall',
                                                                          exterior_wall_standards_construction_type,
                                                                          category))

    exterior_surfaces.setRoofCeilingConstruction(model_find_and_add_construction(model,
                                                                                 climate_zone_set,
                                                                                 'ExteriorRoof',
                                                                                 exterior_roof_standards_construction_type,
                                                                                 category))

    # Interior surfaces constructions
    interior_surfaces = OpenStudio::Model::DefaultSurfaceConstructions.new(model)
    construction_set.setDefaultInteriorSurfaceConstructions(interior_surfaces)
    construction_name = interior_floors
    unless construction_name.nil?
      interior_surfaces.setFloorConstruction(model_add_construction(model, construction_name))
    end
    construction_name = interior_walls
    unless construction_name.nil?
      interior_surfaces.setWallConstruction(model_add_construction(model, construction_name))
    end
    construction_name = interior_ceilings
    unless construction_name.nil?
      interior_surfaces.setRoofCeilingConstruction(model_add_construction(model, construction_name))
    end

    # Ground contact surfaces constructions
    ground_surfaces = OpenStudio::Model::DefaultSurfaceConstructions.new(model)
    construction_set.setDefaultGroundContactSurfaceConstructions(ground_surfaces)
    ground_surfaces.setFloorConstruction(model_find_and_add_construction(model,
                                                                         climate_zone_set,
                                                                         'GroundContactFloor',
                                                                         ground_contact_floor_standards_construction_type,
                                                                         category))

    ground_surfaces.setWallConstruction(model_find_and_add_construction(model,
                                                                        climate_zone_set,
                                                                        'GroundContactWall',
                                                                        ground_contact_wall_standards_construction_type,
                                                                        category))

    # Exterior sub surfaces constructions
    exterior_subsurfaces = OpenStudio::Model::DefaultSubSurfaceConstructions.new(model)
    construction_set.setDefaultExteriorSubSurfaceConstructions(exterior_subsurfaces)
    if exterior_fixed_window_standards_construction_type && exterior_fixed_window_building_category
      exterior_subsurfaces.setFixedWindowConstruction(model_find_and_add_construction(model,
                                                                                      climate_zone_set,
                                                                                      'ExteriorWindow',
                                                                                      exterior_fixed_window_standards_construction_type,
                                                                                      category))
    end
    if exterior_operable_window_standards_construction_type && exterior_operable_window_building_category
      exterior_subsurfaces.setOperableWindowConstruction(model_find_and_add_construction(model,
                                                                                         climate_zone_set,
                                                                                         'ExteriorWindow',
                                                                                         exterior_operable_window_standards_construction_type,
                                                                                         category))
    end
    if exterior_door_standards_construction_type && exterior_door_building_category
      exterior_subsurfaces.setDoorConstruction(model_find_and_add_construction(model,
                                                                               climate_zone_set,
                                                                               'ExteriorDoor',
                                                                               exterior_door_standards_construction_type,
                                                                               category))
    end
    construction_name = exterior_glass_doors
    unless construction_name.nil?
      exterior_subsurfaces.setGlassDoorConstruction(model_add_construction(model, construction_name))
    end
    if exterior_overhead_door_standards_construction_type && exterior_overhead_door_building_category
      exterior_subsurfaces.setOverheadDoorConstruction(model_find_and_add_construction(model,
                                                                                       climate_zone_set,
                                                                                       'ExteriorDoor',
                                                                                       exterior_overhead_door_standards_construction_type,
                                                                                       category))
    end
    if exterior_skylight_standards_construction_type && exterior_skylight_building_category
      exterior_subsurfaces.setSkylightConstruction(model_find_and_add_construction(model,
                                                                                   climate_zone_set,
                                                                                   'Skylight',
                                                                                   exterior_skylight_standards_construction_type,
                                                                                   category))
    end
    if construction_name == tubular_daylight_domes
      exterior_subsurfaces.setTubularDaylightDomeConstruction(model_add_construction(model, construction_name))
    end
    if construction_name == tubular_daylight_diffusers
      exterior_subsurfaces.setTubularDaylightDiffuserConstruction(model_add_construction(model, construction_name))
    end

    # Interior sub surfaces constructions
    interior_subsurfaces = OpenStudio::Model::DefaultSubSurfaceConstructions.new(model)
    construction_set.setDefaultInteriorSubSurfaceConstructions(interior_subsurfaces)
    if construction_name == interior_fixed_windows
      interior_subsurfaces.setFixedWindowConstruction(model_add_construction(model, construction_name))
    end
    if construction_name == interior_operable_windows
      interior_subsurfaces.setOperableWindowConstruction(model_add_construction(model, construction_name))
    end
    if construction_name == interior_doors
      interior_subsurfaces.setDoorConstruction(model_add_construction(model, construction_name))
    end

    # Other constructions
    if construction_name == interior_partitions
      construction_set.setInteriorPartitionConstruction(model_add_construction(model, construction_name))
    end
    if construction_name == space_shading
      construction_set.setSpaceShadingConstruction(model_add_construction(model, construction_name))
    end
    if construction_name == building_shading
      construction_set.setBuildingShadingConstruction(model_add_construction(model, construction_name))
    end
    if construction_name == site_shading
      construction_set.setSiteShadingConstruction(model_add_construction(model, construction_name))
    end

    # componentize the construction set
    # construction_set_component = construction_set.createComponent

    # Return the construction set
    return OpenStudio::Model::OptionalDefaultConstructionSet.new(construction_set)

    # Create a constuction set that is all
  end

```

**Comment by phylroy** [comment]
lib/openstudio-standards/standards/Standards.SpaceType.rb

Extra space type was present for some reason.  Resolved with NRCan version.

**Comment by phylroy** [comment]
lib/openstudio-standards/standards/cbes/cbes.Space.rb
lib/openstudio-standards/standards/cbes/cbes_t24_2005/cbes_t24_2005.Space.rb
lib/openstudio-standards/standards/cbes/cbes_t24_2008/cbes_t24_2008.Space.rb
    Just comments in conflict....

**Comment by phylroy** [comment]
lib/openstudio-standards/standards/necb/NECB2011/building_envelope.rb accepted our changes
```ruby
  def apply_building_default_constructionset(model)

    bldg_def_const_set = model_add_construction_set_from_osm(model: model)
    model.getBuilding.setDefaultConstructionSet(bldg_def_const_set)

  end
```
lib/openstudio-standards/standards/necb/NECB2011/data/space_types.json
     replaced lookup
lib/openstudio-standards/standards/necb/necb_2011/service_water_heating.rb
    Our version of this file was removed to the NECB2011 folder.. So this code should be in our service hot water method. This will need to be review by our SHW master @ckirney .   I will add this code to the top of the NECB2011/service_water_heating.rb file.

**Comment by phylroy** [comment]
lib/openstudio-standards/version.rb
     version bump
openstudio-standards.gemspec
    NREL added openstudio-api-stubs

**Comment by phylroy** [comment]
Keeping all NREL/DOE test as is... 

test/90_1_prm/test_create_performance_rating_method_baseline_bldg_2.rb
test/90_1_prm/test_create_performance_rating_method_baseline_bldg_3.rb
test/90_1_prm/test_create_performance_rating_method_baseline_building.rb
test/circleci_tests.txt
test/doe_prototype/test_add_hvac_systems.rb
test/doe_prototype/test_full_service_restaurant.rb
test/doe_prototype/test_high_rise_apartment.rb
test/doe_prototype/test_hospital.rb
test/doe_prototype/test_large_hotel.rb
test/doe_prototype/test_large_office.rb
test/doe_prototype/test_medium_office.rb
test/doe_prototype/test_mid_rise_apartment.rb
test/doe_prototype/test_outpatient.rb
test/doe_prototype/test_primary_school.rb
test/doe_prototype/test_quick_service_restaurant.rb
test/doe_prototype/test_retail_standalone.rb
test/doe_prototype/test_secondary_school.rb
test/doe_prototype/test_small_hotel.rb
test/doe_prototype/test_small_office.rb
test/doe_prototype/test_strip_mall.rb
test/doe_prototype/test_supermarket.rb
test/doe_prototype/test_warehouse.rb

**Comment by phylroy** [comment]
lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb
lib/openstudio-standards/prototypes/common/objects/Prototype.ServiceWaterHeating.rb
lib/openstudio-standards/standards/Standards.ChillerElectricEIR.rb
test/necb/test_necb_space_types_default_constructions_set.rb
# using standards_lookup_table_first instead of model_find_object

lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb
#added message for sizing run failure. 

test/circleci_tests.txt
#removed necbg buildings from circleci test for now. 

test/helpers/compare_models_helper.rb
#ommited the following object from the OSM compare function and sorted compares. 
    'OS:StandardsInformation:Material',
    'OS:StandardsInformation:Construction'

**Comment by phylroy** [comment]
This taskl is on pause right now.. Things to do when back
1. Fix NREL's VAV tests
2. Examine renaming of Mixers and Splitters make sense as well as HVAC renaming. 
3. Rework the speedy local tests 
3. SHW revamp with @ckirney

**Comment by ckirney** [comment]
Replaced all instances of '"service_water_heating_target_temperature": 140.0,' with '"service_water_heating_target_temperature": 60.0,' in the following files: 
lib/openstudio-standards/standards/necb/NECB2011/data/space_types.json
lib/openstudio-standards/standards/necb/NECB2015/data/space_types.json

I do not know why this happened.  "service_water_heating_target_temperature" was set to 60.0 in the space_types.json files before the merge but after it changed to 140.0 for both NECB2011 and NECB2015 (but not NECB2017).  I am concerned other areas of the space_types.json file where modified too.  This resolved the fails described in issue 4 above.

**Comment by phylroy** [comment]
replaced standards data lookups in all these files. 

 lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb
+2 −6  lib/openstudio-standards/standards/Standards.BoilerHotWater.rb
+2 −2  lib/openstudio-standards/standards/Standards.ChillerElectricEIR.rb
+2 −8  lib/openstudio-standards/standards/Standards.CoilCoolingDXMultiSpeed.rb
+4 −10  lib/openstudio-standards/standards/Standards.CoilCoolingDXSingleSpeed.rb
+4 −16  lib/openstudio-standards/standards/Standards.CoilCoolingDXTwoSpeed.rb
+1 −4  lib/openstudio-standards/standards/Standards.CoilHeatingDXMultiSpeed.rb
+2 −8  lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb
+2 −4  lib/openstudio-standards/standards/Standards.CoolingTower.rb
+3 −6  lib/openstudio-standards/standards/Standards.Fan.rb
+14 −20  lib/openstudio-standards/standards/Standards.Model.rb
+2 −4  lib/openstudio-standards/standards/Standards.Pump.rb
+1 −1  lib/openstudio-standards/standards/Standards.Space.rb
+2 −3  lib/openstudio-standards/standards/Standards.SpaceType.rb
+1 −1  lib/openstudio-standards/standards/Standards.WaterHeaterMixed.rb

**Comment by ckirney** [comment]
Created 'corrupt_standards_database' method in NECB2011.rb which adds the arrays in the tables hash of the standards database to the the main portion of the standards database.  Added a call to this method in the initialize method in:
NECB2011.rb
NECB2015.rb
NECB2017.rb

Adjusted the Sydney and Truro .ddy files to match the format of all of the other weather files.

**Comment by ckirney** [comment]
switched to using 'model_find_object', or 'model_find_objects' in the following files:

lib/openstudio-standards/standards/necb/NECB2011/autozone.rb
lib/openstudio-standards/standards/necb/NECB2011/building_envelope.rb
lib/openstudio-standards/standards/necb/NECB2011/hvac_systems.rb
lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb
lib/openstudio-standards/standards/necb/NECB2011/service_water_heating.rb
lib/openstudio-standards/standards/necb/NECB2015/hvac_systems.rb
lib/openstudio-standards/standards/necb/NECB2015/lighting.rb
lib/openstudio-standards/standards/necb/NECB2015/qaqc/necb_2015_qaqc.rb
test/necb/test_necb_default_spacetypes.rb
test/necb/test_necb_default_system_selection.rb
test/necb/test_necb_schedules.rb
test/necb/test_necb_shw.rb
test/necb/test_necb_space_types_default_constructions_set.rb
