### ISSUE TITLE
Power Bi tables for OEE report (statement of work)

### ISSUE THREAD

**Issue by anttoms21** [canmet-energy/btap_tasks#235]
### Description
Use Power BI to create tables that will be used for the OEE report.  There will be three cities and seven buildings types that needs to be taken into account.  As well use the data from 2015 and 2017.  

### Approach
Use Power BI

### Testing Plan
Create the tables and show Phylroy/Chris to see if there is anything to add 

### Waiting On
Chris to create a measure and add Truro and Sydney

### Repositories Involved

https://github.com/NREL/openstudio-standards/tree/nrcan

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	

|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by phylroy** [comment]
@anttoms21 Check with Mike that you can create reports like this for any model/run. Either in powerbi or ruby. Lets review where you are at tomorrow as I will probably need to take over while you are gone next week. 
[2015 and 2017 diff.xlsx](https://github.com/canmet-energy/btap_tasks/files/3113563/2015.and.2017.diff.xlsx)
