### ISSUE TITLE
PowerBI PANDAS Investigation

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#238]
### Description
Investigate if PANDAS can be used to replace the data cleaning aspect for BTAP. 
### Approach
1. Installation of Python and PANDAS either on windows or in the BTAP container. Record the installation process for both in this task as a comment. 
2. Create a simple dataframe and try to access it from PowerBI.. make up the data in the dataframe...Ensure this workflow can work. 
3. Use Python to load simulations.json into a dataframe and save as a pickle or an HDF5. This will cut the time loading the file everytime into a fraction.  Read up on pickle and HDF5
4. Create a git project that has the start of this python script. 
5. Create dataframes that replicate the intermediate tables you have already created in PowerBI. Start with a simple one and go from there.

**Comment by anttoms21** [comment]
Installing Python and Pandas

Start by installing Python with Pycharm using the link below.  Make sure to use the Community version as it is free!
https://www.jetbrains.com/pycharm/

You can try to open the IDE but there will probably be an error message.  If the error message occurs go to the link below and download python. This should fix the error message!
https://www.python.org/downloads/

Now you should have access to PyCharm.  To get panda go to File on the top left corner, click on settings.
Under Projects there is project interpreter.  From here search up Pandas and install

Now you should have pandas with your PyCharm.

**Comment by anttoms21** [comment]
How to get Pandas and Python working in PowerBI

BE AWARE: There have been many reports that 3.7 is not working ideally, and there are a lot of issues with getting python with power bi.  Therefore please use 3.6 version.

1.  Go to file -> options and settings -> options -> preview features and select python script on
2. Go to file -> options and settings -> options -> python scripting make sure that the detected python home directory is correct.

 If this works congrats, but I will also post a bunch of issues I also ran into.

ADO.net error, python exe not found... you need to copy your python folder into the ADO.net folder.  This is probably in C drive somewhere.

PythonScriptWrapper.PY - this could be a couple of things, read the details.  The errors i got were pandas missing and matplotlib missing.  Go to the command line,  type: get-pip.py

To fix thematplotlib
in command line type: pip install matplotlib

To fix pandas 
in command line type: pip install pandas

**Comment by phylroy** [comment]
@phylroy to put instruction into Python Pandas project
