### ISSUE TITLE
NZEB-HVAC

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#249]
### Description
Review the NZEB measure that NREL has put together and

1. Have it use the NECB  autozoning
2. Have it work with Auto-costing. 

### Approach
Created a test harness for costing here to help go over error and missing items. 
https://github.com/canmet-energy/btap_costing/blob/master/measures/btap_results/tests/test_nzeb_hvac_costing.rb

### Testing Plan
TBD

### Waiting On
Nothing

**Comment by jblake59** [comment]
This branch (nrcan_249) has been deleted as this issue is closed.
