### ISSUE TITLE
Tier2&3 costing

### ISSUE THREAD

**Issue by edwardv720** [canmet-energy/btap_tasks#250]
### Description
Create spec info required for costing NECB 2017 Tier 2, Tier 3 buildings for PCF 1527

### Approach
Edward to:

1. - Upload osm for Phylroy to generate qaqc.json for Mike's use in developing HVAC spreadsheet- DONE

2. - Upload excel containing hvac system (e.g. vrf, doas, ptac)- DONE
3. - Calc piping length for vrf in offices & highrise
4. - Update input variable range for tier 2 and 3

https://github.com/canmet-energy/btap

**Comment by edwardv720** [comment]
@phylroy , could you run the tier 2 and 3 osm share the json with me? It would be more efficient than for me to manually open and record every wall/roof/window uvalues, boiler efficiency, infiltration rate etc.

**Comment by phylroy** [comment]
Thanks for creating the task. Could you sent email to everyone. 

I sure can do what you asked before as soon as you upload them to the branch and put into tier folders as mike requested into tier folders.  

To be consistent, could you name the file by the <building_type-vintage-epw_file-tier.osm>.  Like so:

FullServiceRestaurant-NECB2017-CAN_AB_Banff.CS.711220_CWEC2016_Tier2.osm

I will name them accordingly as 

 FullServiceRestaurant-NECB2017-CAN_AB_Banff.CS.711220_CWEC2016-Tier2.json

Here is the branch I sent earlier. 

https://github.com/canmet-energy/btap/tree/pcf1527


Thanks, 

Phylroy

**Comment by phylroy** [comment]
Completed batch development. Waiting on osm files. 
```ruby
require '/usr/local/openstudio-2.8.1/Ruby/openstudio'
require 'openstudio-standards'
require 'openstudio/ruleset/ShowRunnerOutput'
require 'minitest/autorun'
require 'optparse'
begin
  require 'openstudio_measure_tester/test_helper'
rescue LoadError
  puts 'OpenStudio Measure Tester Gem not installed -- will not be able to aggregate and dashboard the results of tests'
end
require_relative '../measure.rb'
require 'fileutils'
require 'minitest/unit'
require 'optparse'


class BTAPResults_Test < Minitest::Test


  def test_osm_files()
    #Folder to process costing data. 
    osm_folder = '/home/osdev/btap_costing/measures/btap_create_necb_prototype_building/tests/regression_models/'
    osm_files = BTAP::FileIO.get_find_files_from_folder_by_extension( osm_folder , 'osm')
    osm_files.each do |osm_file|

      standard = Standard.build("NECB2017")
      model_file = osm_file
      model_name = File.basename(model_file)
      model = BTAP::FileIO.load_osm(model_file)
      epw_file = model.getBuilding.name.get.match(/^(\S*?)-(.*)$/)[2]

      #create folders
      test_dir = "#{File.dirname(__FILE__)}/output"
      if !Dir.exists?(test_dir)
        Dir.mkdir(test_dir)
      end
      run_dir = "#{test_dir}/#{model_name}"
      if !Dir.exists?(run_dir)
        Dir.mkdir(run_dir)
      end


      #run simulation
      #
      BTAP::Environment::WeatherFile.new(epw_file).set_weather_file(model)
      standard.model_run_simulation_and_log_errors(model, run_dir)

      # mimic the process of running this measure in OS App or PAT
      model_out_path = "#{run_dir}/final.osm"
      workspace_path = "#{run_dir}/run/in.idf"
      sql_path = "#{run_dir}/run/eplusout.sql"
      cost_result_json_path = "#{run_dir}/cost_results.json"

      #create osm file to use mimic PAT/OS server called final
      model.save(model_out_path, true)

      # set up runner, this will happen automatically when measure is run in PAT or OpenStudio. Ensure files exist.
      runner = OpenStudio::Measure::OSRunner.new(OpenStudio::WorkflowJSON.new)
      assert(File.exist?(model_out_path), "Could not find osm at this path:#{model_out_path}")
      runner.setLastOpenStudioModelPath(OpenStudio::Path.new(model_out_path))
      assert(File.exist?(workspace_path), "Could not find idf at this path:#{workspace_path}")
      runner.setLastEnergyPlusWorkspacePath(OpenStudio::Path.new(workspace_path))
      assert(File.exist?(sql_path), "Could not find sql at this path:#{sql_path}")
      runner.setLastEnergyPlusSqlFilePath(OpenStudio::Path.new(sql_path))

      # temporarily change directory to the run directory and run the measure
      start_dir = Dir.pwd
      begin
        # create an instance of the measure and runner
        measure = BTAPResults.new
        arguments = measure.arguments()
        argument_map = OpenStudio::Measure.convertOSArgumentVectorToMap(arguments)
        assert_equal(10, arguments.size)

        hourly_data = arguments[0].clone
        assert(hourly_data.setValue("false"))
        argument_map['generate_hourly_report'] = hourly_data

        output_diet = arguments[1].clone
        assert(output_diet.setValue(false))
        argument_map['output_diet'] = output_diet

        envelope_costing = arguments[2].clone
        assert(envelope_costing.setValue(true))
        argument_map['envelope_costing'] = envelope_costing

        lighting_costing = arguments[3].clone
        assert(lighting_costing.setValue(true))
        argument_map['lighting_costing'] = lighting_costing

        boilers_costing = arguments[4].clone
        assert(boilers_costing.setValue(true))
        argument_map['boilers_costing'] = boilers_costing

        chillers_costing = arguments[5].clone
        assert(chillers_costing.setValue(true))
        argument_map['chillers_costing'] = chillers_costing

        cooling_towers_costing = arguments[6].clone
        assert(cooling_towers_costing.setValue(true))
        argument_map['cooling_towers_costing'] = cooling_towers_costing

        shw_costing = arguments[7].clone
        assert(shw_costing.setValue(true))
        argument_map['shw_costing'] = shw_costing

        ventilation_costing = arguments[8].clone
        assert(ventilation_costing.setValue(true))
        argument_map['ventilation_costing'] = ventilation_costing

        zone_system_costing = arguments[9].clone
        assert(zone_system_costing.setValue(true))
        argument_map['zone_system_costing'] = zone_system_costing


        Dir.chdir(run_dir)
        # run the measure
        measure.run(runner, argument_map)
        result = runner.result
        show_output(result)
        assert_equal('Success', result.value.valueName)
      ensure
        Dir.chdir(start_dir)
      end
      assert(File.exist?(cost_result_json_path), "Could not find costing json at this path:#{cost_result_json_path}")
    end
  end
end
```

**Comment by phylroy** [comment]
@edwardv720 from Chris' email. 


Hi Edward,

Could you please make sure that your DOAS airloop names all start with ‘Sys_1’ (that exact string, including capitalizing the first letter)?  We use that string to ensure it is costed properly.

Thanks,
Chris

**Comment by phylroy** [comment]
@edwardv720,  @ckirney  means to update the *osm*  files in the above comment. Just to be clear.

**Comment by edwardv720** [comment]
- "Sys_1"  added
- osm file renamed (Tier osm>T2/T3)
- HVAC system descriptive excel added

**Comment by edwardv720** [comment]
**NOTE*** 
The med & large office osms have a large number of unmet hours - a tweak for those wll come soon.

**Comment by phylroy** [comment]
@edwardv720  when creating directories or filenames for development, please do not use spaces. Command line scripts may sometimes see spaces as two arguments and cause problems on windows and Linux. . So convention doing simulation work here is to not to use spaces. If you notice, most of the folders and names are kept to a lower_case_with_underscores to avoid this problem where possible.

**Comment by phylroy** [comment]
@edwardv720 this is also part of the reason to rename the osm  files to the building_type standard names and climate file ids to keep convention.

**Comment by phylroy** [comment]
> **NOTE***
> The med & large office osms have a large number of unmet hours - a tweak for those wll come soon.

@edwardv720 should I hold off on the runs? I have a meeting at 10am-1am.

**Comment by edwardv720** [comment]
The hvac systems will remain the same. If they're going to help Mike on setting up templates then they'll be fine.

**Comment by edwardv720** [comment]
> 
> 
> @edwardv720 when creating directories or filenames for development, please do not use spaces. Command line scripts may sometimes see spaces as two arguments and cause problems on windows and Linux. . So convention doing simulation work here is to not to use spaces. If you notice, most of the folders and names are kept to a lower_case_with_underscores to avoid this problem where possible.

Gotcha! I've renamed the folders

**Comment by phylroy** [comment]
@edwardv720 merged your pull request that renamed the  folders. 

Running costing now..  It is running single thread...if we have to do this again, or if it is slow, I will parallelize the script.  Off to my meeting.

**Comment by phylroy** [comment]
@edwardv720 added some of the costed JSON output.. it for some reason failed at T3 Large Office. The last successful run was for RetailStripmall/RetailStripmall-CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016_Tier3.osm.json'
[pcf1527 c0e1d95] added some of the costed JSON output.. it for some reason failed at T3Large Office. The last successful run was for RetailStripmall/RetailStripmall-CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016_Tier3.osm.json

https://github.com/canmet-energy/btap/commit/c0e1d9597e467a0d16fb7574b30074096a2cba50

**Comment by phylroy** [comment]
@edwardv720 Found out why they failed.  The naming convention was not employed on all the files in the same manner.  For example

    LargeOffice_CAN_ON_Windsor.Intl.AP.715380_CWEC2016_Tier3.osm
and
    LargeOffice-CAN_ON_Windsor.Intl.AP.715380_CWEC2016_Tier2.osm.

One has an trailing underscore, while the other has a minus sign after the building_type.....  Either way is fine, but maintaining consistency in naming scripting is key.  I'll make the fix and re-run the script on the remaining files.

**Comment by edwardv720** [comment]
> 
> 
> @edwardv720 Found out why they failed. The naming convention was not employed on all the files in the same manner. For example
> 
> ```
>     LargeOffice_CAN_ON_Windsor.Intl.AP.715380_CWEC2016_Tier3.osm
> ```
> 
> and
> 
> ```
>     LargeOffice-CAN_ON_Windsor.Intl.AP.715380_CWEC2016_Tier2.osm.
> ```
> 
> One has an trailing underscore, while the other has a minus sign after the building_type..... Either way is fine, but maintaining consistency in naming scripting is key. I'll make the fix and re-run the script on the remaining files.

@phylroy fixed naming and added piping layout files; made pull request

**Comment by phylroy** [comment]
Wednesday Notes: 
Mike Debrief: 
		* 2 days a city per simulation to develop. 8 days to accomplish the baseline only.
		* Solution Set Costing 12 days per tier.
This is much larger to do at the moment. So we will will have to reduce scope from the 72 costed scenarios to something more realistic. 

Iain mentioned that perhaps Morrison H would have something that could help out albeit at a lower resolution.

**Comment by phylroy** [comment]
@edwardv720 @mlubun  Json runs are completed and posted 

https://github.com/canmet-energy/btap/commit/3f99cd389945a3c2a303ed425f8ab75909a731fd

@mlubun  you can see the files here. 
https://github.com/canmet-energy/btap/tree/pcf1527/Tier_osm

**Comment by IainMacdonald** [comment]
> 
> 
> Wednesday Notes:
> Mike Debrief:
> * 2 days a city per simulation to develop. 8 days to accomplish the baseline only.
> * Solution Set Costing 12 days per tier.
> This is much larger to do at the moment. So we will will have to reduce scope from the 72 costed scenarios to something more realistic.
> 
> Iain mentioned that perhaps Morrison H would have something that could help out albeit at a lower resolution.

@phylroy - just to be clear this is the time it will take to generate the spec files for the cost consultant. I need to add time for the cost consultant to process that data on top of these time estimates.

**Comment by mlubun** [comment]
Did Victoria Secondary School costing spec yesterday (1.5 hours).  had to fix a number of items in the template as the 2017 reference school is all-electric and my template assumes hot water heating.  used the QAQC  run on July 17 for the reference data and costing.  That version includes the flex duct lengths and diameters and tells you the number of PTACs and baseboard heaters required (using industry standard sizes for ptacs and baseboard electric).  Attached the .xls.  Please look over secondary school as this is the only 1 done.  I am working on the rest for Victoria.
[baselinevictoria.xlsx](https://github.com/canmet-energy/btap_tasks/files/3530487/baselinevictoria.xlsx)

**Comment by phylroy** [comment]
@IainMacdonald  Here is a ~400 point optimization FSR in victoria (I'm using this for testing because it simulates the fastest)

You can see the 4 localized optimium 'sets'. Some be 'selected out' if needed.  

(Y)This is costing anything that the costing can do at the moment 
(X) the percent difference from necb2017 / 100.0 (X) (-negative is better.) 

I figure this is enough granularity to give an idea of what we are up to. I'll be running the 6 building types in victoria next. 

![image](https://user-images.githubusercontent.com/5103270/63526413-63032100-c4cd-11e9-8622-5c59e6308a7a.png)

**Comment by IainMacdonald** [comment]
@phylroy - awesome. For Friday are you preparing a presentation that would include this or do you want us to include it in our summary? Either way I think it will be essential that the limits of BTAP costing are explicit in the presentation (i.e. specify exactly what is and is not included).
From this there looks to be a lot of Tier 2 solutions and quite a few Tier 3 solutions. This is good.

**Comment by phylroy** [comment]
@IainMacdonald lets chat about it. I may have a few slides like this, and perhaps it would be beneficial to go over the measures and the limits we are looking at. @edwardv720 have you commited the updated excel file with the variable values for each measure? When you do, please put a link here. I'll review values and run them when I have them.

**Comment by phylroy** [comment]
Added options file for costing/optimization runs.

**Comment by mlubun** [comment]
Attached is the completed spreadsheet for Victoria for all bldg 6 building types.  I have an issue with medium and large office related to the reheat coils.  We cost them, but do not report the sizes in the .json.  So when I tried running it in O/S to generate the .sql it runs, but crashes at the end.  I will look at what is going on tommorrow.  Everything else is done.

[baselinevictoria.xlsx](https://github.com/canmet-energy/btap_tasks/files/3532059/baselinevictoria.xlsx)

**Comment by IainMacdonald** [comment]
Costing for this was completed by Hanscomb.
