### ISSUE TITLE
Rake test for costing creating inconsistent results

### ISSUE THREAD

**Issue by jblake59** [canmet-energy/btap_tasks#252]
### Description
The rake costing test "test:costing-tests" is running successfully for some files and not for others and the file comparison between test costs and expected costs is not showing a difference in cost data but in alignment of the test file with expected results file due to an extra CR (possibly). When running all building types, the problem files appear to change from one run to the next. The problem seems to only occur with 2011 template files although this hasn't been exhaustively tested.

### Approach
Attempt to identify the cause by running individual files through this test. @ckirney was able to generate the problem with SmallOffice.

### Testing Plan
Test all building types in all vintages.

### Waiting On
Available time. 

### Repositories Involved

https://github.com/canmet-energy/btap-costing

### Select the Project Code you will be charging to 2018-2019

|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by ckirney** [comment]
The report from rake test:costing-tests said that LargeOffice, SmallOffice, FullServiceRestaurant and MediumOffice for Prince George had differences between the expected and test results.  This was not true.  Of the reported failures only SmallOffice had differences and they were present for both Whitehorse and Prince George.  The only difference was the addition of one or two extra blank characters at the beginning of the file.

The rake test:costing-tests output said that there were no differences between the test result and expected result files for Warehouse in both Whitehorse and Prince George.  This was not true as differences were present between the test and expected results for Warehouse at both locations.  

Although the rake test:costing-tests output is unreliable, *test_result.cost.json files were properly generated in the 'regression_files' folder for only those tests for which the test and expected results differed.

**Comment by ckirney** [comment]
Two separate arrays were used to determine the files being tested and what was reported.  Only one is used now so the reported and actual errors should match now.
