### ISSUE TITLE
ECM: Lighting Power Density Measure

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#29]
class name BTAPLightingPowerDensityMeasure

Requirements: 
A measure that will adjust the LPD max value for selected or all spacetypes. 
This measure will need to adjust the LPD by scalar or actual value. 
Have BTAP results provide an overall LPD per unit area to examine changes at high-level to LPD if this does not already exist, potentially the LPD per spacetype. This will help with debugging potentially. 
## Measure arguments requirements: 

The optimization routines will not run the do nothing 'baseline' unless explicity noted in the discrete variable list. For this reason, all measure are required to have a baseline input.

For strings it is "baseline"
For floats and integers is is -9999999999 (10 '9's) . When the measure received this value, the ecm_* variable must be set to 'baseline' withing the measure code for subsequent measure purposes and analysis.

*  string array: ecm_list_of_space_types_to_apply ( default "all")
*  string: ecm_type  ( ["value","percent"] default "percent") 
*  float:   ecm_value  ( default .80)

## Tests
Measure test 1 : Run against an archetype varying varialbles.  Scan the resulting osm model for the changes. Compare against an expected  resulting using the mini-test assert. If the same, pass otherwise fail with an appropriate message. 
 

Once again.. there may be examples of this. So look in standards and the BCL for things already done.  Ideally standards first. 

This measure should be made compatible with Jeff Blake's work on lighting costing.  Ensure you discuss this with him during development. 

# Pull request requirements. 
Once measure and tests are completed,  add it to the BTAP repository in the measures folder and name it "BTAPFDWRRatio" name the class the same way. with tests and add tests to Rakefile and submit a pull request. 

Note: This measure may exists in the BCL, please review the code example there and leverage what you require to create this measure in the BTAP project.

**Comment by IainMacdonald** [comment]
The pull request requirements has the wrong class name!

**Comment by IainMacdonald** [comment]
Jeff - what variables would you need for the costing?

**Comment by jblake59** [comment]
@IainMacdonald : Don't know yet! I've only just started the lighting cost work and it was put on hold by @phylroy in order to complete NECB2015 issues first. The costing class also needs to be "re-factored" (see issue #25). Also, if you're going to handle this issue, please assign it to yourself.

**Comment by MarianaNRC** [comment]
we're working on this one just now. Do we need to call the args ecm_* or can we give them more logical names (e.g. lpd_value)?

**Comment by IainMacdonald** [comment]
I'm confused about the 'baseline' requirements. Is there an example in an existing measure that someone can point us to?
