### ISSUE TITLE
NECB 2015 QAQC Run Failures. 

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#42]
Tyson determined that some NECB 2015 runs are failing.  The error logger that is used to determine the errors has not been ported to the new PAT way of doing things. 
1. Determine what errors are occuring in the National runs and indicate if there is a pattern. (Edward)  
2. Determine if any of the current standards tasks are already in queue to fix the problems.  (Marianne) 
3.  Fix the script that generated the errors that determined if there are issues.  (Padmassun & Marianne)

**Comment by padmassun** [comment]
Also Fixed the errors of the downloading script. 
Main errors:
https://github.com/canmet-energy/btap_gather_results/commit/0eac7dadf783e08402e2db665bbd2479c7ef9371 
https://github.com/canmet-energy/btap_gather_results/commit/9db7fbb58734fbfb75a6ef20204392877f6b75aa

I will be updating the instructions shortly...

**Comment by IainMacdonald** [comment]
Kamel has implemented a solution. Weekly runs required to check if this is the solution.
