### ISSUE TITLE
Make BTAP measures runnable in OS model editor/app

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#50]
Currently the NECB BTAP measures require a recent version of standards nrcan branch to run. This prevents users on windows from running the measures and only can be run on PAT with nrcan branch server. 

To mitigate this a mechanism needs to be created to add updates from the nrcan branch directly to the measures via a rakefile command. This will allow users to use our measures regardless of OS version and standards version.

**Comment by IainMacdonald** [comment]
Paused until 2.5.2 released (expected end june)
