### ISSUE TITLE
NECB 2015 warning/error messages - for cross reference 

### ISSUE THREAD

**Issue by edwardv720** [canmet-energy/btap_tasks#54]
Warnings and errors from the 16 archetypes using Edmonton weather. Requiring cross reference with @padmassun.

Most warnings/errors are benign (e.g. PLF reset to 1 when PLR = 0.99)

Some are minor, where incorrect inputs are used (e.g. shadow calculation frequency set to 15000 instead of 20)

One unresolved issue:  Cooling Coil has leaving humidity ratio > entering humidity ratio.
Outlet of cooling coil has greater humidity than the inlet in sizing calculation. This is because the humidity ratio of the 2 nodes are 
 calculated independently. The outlet node humidity is set to 90% RH at the sizing object's central cooling SAT. But the inlet is computed
 by mixing the average return air's humidity + outdoor air humidity. Some zones have low humidity (e.g. 0.002). Hence, the inlet humdiity is
 low.

[Hospital warning and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058463/Hospital.warning.and.errors.txt)

[full service restaurant Edmonton INTL.txt](https://github.com/canmet-energy/btap_tasks/files/2058465/full.service.restaurant.Edmonton.INTL.txt)

[quick service restaurant warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058464/quick.service.restaurant.warnings.and.errors.txt)

[Highrise apartment Edmonton .txt](https://github.com/canmet-energy/btap_tasks/files/2058466/Highrise.apartment.Edmonton.txt)

[warehouse edmonton warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058468/warehouse.edmonton.warnings.and.errors.txt)

[Large hotel edmonton warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058472/Large.hotel.edmonton.warnings.and.errors.txt)

[Medium office warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058474/Medium.office.warnings.and.errors.txt)

[Small hotel warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058481/Small.hotel.warnings.and.errors.txt)

[Outpatient warning and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058482/Outpatient.warning.and.errors.txt)

[Retail standalone warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058480/Retail.standalone.warnings.and.errors.txt)

[Secondary School warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058478/Secondary.School.warnings.and.errors.txt)

[small office warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058479/small.office.warnings.and.errors.txt)

[Large Office warnings and erors.txt](https://github.com/canmet-energy/btap_tasks/files/2058477/Large.Office.warnings.and.erors.txt)

[Midrise APT Edmonton warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058473/Midrise.APT.Edmonton.warnings.and.errors.txt)

[Primary school warnings and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058470/Primary.school.warnings.and.errors.txt)

[Retail strip mall warning and errors.txt](https://github.com/canmet-energy/btap_tasks/files/2058471/Retail.strip.mall.warning.and.errors.txt)

**Comment by padmassun** [comment]
For now the Only errors that I am aware of are the `**  Fatal  ** Autosizing of cooling tower UA failed for tower COOLING TOWER SINGLE SPEED 1` mentioned at https://github.com/canmet-energy/btap_tasks/issues/42 . This issue was fixed. 

I have yet to run another simulation for NECB 2015. After I run those, I will post an update.

**Comment by edwardv720** [comment]
Yeah that is the only fatal error I found as well.

**Comment by padmassun** [comment]
Re: Hostpital Issue: https://github.com/NREL/openstudio-standards/issues/253
>**These surfaces currently have an adiabatic boundary condition; they should have outdoor boundary conditions- according to DOE model in sketchup**
			Surfaces: ER_NURSESTN_LOBBY_FLR_1-5, IC_PATROOM3_MULT6_FLR_2-5

ENERGYPLUS ERROR MESSAGE:
   ** Warning ** BuildingSurface:Detailed="ER_NURSESTN_LOBBY_FLR_1-5", Sun Exposure="SUNEXPOSED".
   **   ~~~   ** ..This surface is not exposed to External Environment.  Sun exposure has no effect.
   ** Warning ** BuildingSurface:Detailed="IC_PATROOM3_MULT6_FLR_2-5", Sun Exposure="SUNEXPOSED".
   **   ~~~   ** ..This surface is not exposed to External Environment.  Sun exposure has no effect.
   
   OSM OBJECT:
   OS:Surface,
  {170c1691-f286-4962-b7e5-943e4481b43a}, !- Handle
  ER_NurseStn_Lobby_Flr_1-5,              !- Name
  Wall,                                   !- Surface Type
  {80c579d6-a5b3-44fb-b6b6-332ed338c748}, !- Construction Name
  {aead3fc1-6c8e-4cdb-9754-f28c1cd36458}, !- Space Name
  Adiabatic,                              !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  SunExposed,                             !- Sun Exposure
  WindExposed,                            !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  -24.384, -35.052, 4.2672,               !- X,Y,Z Vertex 1 {m}
  -24.384, -35.052, 0,                    !- X,Y,Z Vertex 2 {m}
  -6.09600000000002, -35.052, 0,          !- X,Y,Z Vertex 3 {m}
  -6.09600000000002, -35.052, 4.2672;     !- X,Y,Z Vertex 4 {m}

**Zones not fully enclosed**

	ENERGYPLUS ERROR MESSAGE:
	** Warning ** CalculateZoneVolume: 29 zones are not fully enclosed. For more details use:  Output:Diagnostics,DisplayExtrawarnings;

This might have to be opened again.

**Comment by edwardv720** [comment]
I've recorganized them to see what is more pressing and errors that are specific to which building. I've also added a bit more of what I think the building specific warnings are (non geoemtric issues).


[Building specific errors.txt](https://github.com/canmet-energy/btap_tasks/files/2073490/Building.specific.errors.txt)

[Recurring errors amongst buildings.txt](https://github.com/canmet-energy/btap_tasks/files/2073487/Recurring.errors.amongst.buildings.txt)



[Recurring errors - potential errors.txt](https://github.com/canmet-energy/btap_tasks/files/2073480/Recurring.errors.-.potential.errors.txt)
[Recurring errors - solved.txt](https://github.com/canmet-energy/btap_tasks/files/2073481/Recurring.errors.-.solved.txt)
[Recurring errors - unsolved.txt](https://github.com/canmet-energy/btap_tasks/files/2073482/Recurring.errors.-.unsolved.txt)

**Comment by phylroy** [comment]
@edwardv720 to create issues based on each warning that is deemed to be causing significant problems

**Comment by edwardv720** [comment]
#87 Shadow calculation frequency

**Comment by padmassun** [comment]
#87 Shadow calculation frequency
~#88 Outpatient-zone not closed~ Complete
~#89 Retail standalone - Zone solar distribution (non convex zone)~ Complete
~#90 Hospital - boundary conditions of surfaces~ Complete
~#91 Hospital - zone not fully enclosed~ Complete
~#92 Hospital - adjacent zones with different mutipliers sharing a common surface~ Complete
#93 Nominal pumping power is sized to 0W

**Comment by padmassun** [comment]
All the issues opened by @edwardv720 are resolved

**Comment by edwardv720** [comment]
The EnergyPlus errors/warnings found in tasks 87-93 have been cleared.
