### ISSUE TITLE
Identify all non-used or duplicate method present in the BTAP folder. 

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#77]
Go through all the methods in the BTAP Folder Module and determine if
1) The method is duplicated anywhere else in the standards project. 
2) Is the method not called from anywhere in standards or BTAP measures or measures_development. 
 Create a report table with the file, method_name, item1, and item 2

You may use ruby tools out there to do this task as this is not a new thing.  I expect this to take <2 days to finish abouts. 

The goal is to inform how we can reduce redundancy and confusion and what could be added to the Standards and NECB class structure and what are utilities.

**Comment by padmassun** [comment]
[BTAP_usage.xlsx](https://github.com/canmet-energy/btap_tasks/files/2341087/BTAP_usage.xlsx)
