### ISSUE TITLE
Separate QAQC and Data Gathering

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#86]
I've notice that there are a lot of things mixed in QAQC that are more data oriented. I would like you to examine the data aspects and the QAQC aspects and separate them.

**Comment by padmassun** [comment]
`init_qaqc`: Will generate the full qaqc json (Base + QAQC) - Default method called for CI and BTAPResults measure
`qaqc_only`: Will generate the QAQC only `[New method]`
`create_base_data`: Will generate the Base data only `[Renamed method: create_base_qaqc]`

**Comment by padmassun** [comment]
Resolved
