### ISSUE TITLE
Primary School- Shadow calculation frequency

### ISSUE THREAD

**Issue by edwardv720** [canmet-energy/btap_tasks#87]
- Calculation frequency for Shadow Calculation is set to 15000 but the default is only 20.
-  15000 is the default for the "Maximum Figures in Shadow Overlap Calculations" input

	ENERGYPLUS ERROR MESSAGE:
   ** Warning ** ShadowCalculation: suspect Calculation Frequency
   **   ~~~   ** Value entered=[15000], Shadowing Calculations will be inaccurate.

**Comment by padmassun** [comment]
NOTE: This issue is also present in ASHRAE PrimarySchool Models. 

The Calculation frequency for Shadow Calculation was changed from 15000 to 20. See Commit:  https://github.com/NREL/openstudio-standards/commit/b2dcb169cdcf21ea951dcf3923abcd468c8ec64c

Waiting for CircleCI test to pass.

**Comment by padmassun** [comment]
Merged
