### ISSUE TITLE
NECB2015 E+ msg: Retail standalone - Zone solar distribution (non convex zone)

### ISSUE THREAD

**Issue by edwardv720** [canmet-energy/btap_tasks#89]
The zone in question is a non-convex zone  but Solar Distribution = FullInteriorExterior was set. FullInteriorExterior only works if the zone is convex. 
   Simulation Settings> Simulation Control>SolarDistribution needs to use FullExterior.
   The error shows up for one zone only (SP-CORE_RETAIL SYS-3 FLR-1 SCH-C HPLCMT-EAST ZN)

	ENERGYPLUS ERROR MESSAGE:
   ** Severe  ** Problem in interior solar distribution calculation (CHKBKS)
   **   ~~~   **    Solar Distribution = FullInteriorExterior will not work in Zone=SP-CORE_RETAIL SYS-3 FLR-1 SCH-C HPLCMT-EAST ZN
   **   ~~~   **    because vertex 2 of back surface=CORE_RETAIL_WALL_EAST_1 is in front of receiving surface=CORE_RETAIL_ROOF
   **   ~~~   **    (Dot Product indicator=459.6689)
   **   ~~~   **    Check surface geometry; if OK, use Solar Distribution = FullExterior instead.

**Comment by IainMacdonald** [comment]
Note sure what the diff is as the whole file is marked as different! I do not think splitting the roof is enough. The main zone needs to be made convex - this is easily done by moving the wall at the entrance zone back a little (so its in line with the other walls and the zone is then convex.

**Comment by padmassun** [comment]
I think it was the line endings that caused the whole doff to be different.. I've used Sketchup to modify the geometry and split the roof. 

![image](https://user-images.githubusercontent.com/24966493/42966549-8852cfa6-8b6b-11e8-9143-480061924806.png)

**Comment by IainMacdonald** [comment]
Its not just the roof that's the problem. Its the whole zone. You need to remove the bit of the zone that is to the left of the red line in the image. Easily done by extending the doorway zone back to where the red line is.

**Comment by padmassun** [comment]
I've tested this model after splitting the roof, and that problem was solved.

[eplusout.err.txt](https://github.com/canmet-energy/btap_tasks/files/2211469/eplusout.err.txt)

**Comment by IainMacdonald** [comment]
weird!

**Comment by padmassun** [comment]
Resolved, and merged.
