### ISSUE TITLE
NECB2015 E+ msg: Hospital - boundary conditions of surfaces 

### ISSUE THREAD

**Issue by edwardv720** [canmet-energy/btap_tasks#90]
These surfaces currently have an adiabatic boundary condition; they should have outdoor boundary conditions- according to DOE model in sketchup.
			Surfaces: ER_NURSESTN_LOBBY_FLR_1-5, IC_PATROOM3_MULT6_FLR_2-5

	ENERGYPLUS ERROR MESSAGE:
   ** Warning ** BuildingSurface:Detailed="ER_NURSESTN_LOBBY_FLR_1-5", Sun Exposure="SUNEXPOSED".
   **   ~~~   ** ..This surface is not exposed to External Environment.  Sun exposure has no effect.
   ** Warning ** BuildingSurface:Detailed="IC_PATROOM3_MULT6_FLR_2-5", Sun Exposure="SUNEXPOSED".
   **   ~~~   ** ..This surface is not exposed to External Environment.  Sun exposure has no effect.
   
   OSM OBJECT:
   OS:Surface,
  {170c1691-f286-4962-b7e5-943e4481b43a}, !- Handle
  ER_NurseStn_Lobby_Flr_1-5,              !- Name
  Wall,                                   !- Surface Type
  {80c579d6-a5b3-44fb-b6b6-332ed338c748}, !- Construction Name
  {aead3fc1-6c8e-4cdb-9754-f28c1cd36458}, !- Space Name
  Adiabatic,                              !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  SunExposed,                             !- Sun Exposure
  WindExposed,                            !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  -24.384, -35.052, 4.2672,               !- X,Y,Z Vertex 1 {m}
  -24.384, -35.052, 0,                    !- X,Y,Z Vertex 2 {m}
  -6.09600000000002, -35.052, 0,          !- X,Y,Z Vertex 3 {m}
  -6.09600000000002, -35.052, 4.2672;     !- X,Y,Z Vertex 4 {m}

**Comment by padmassun** [comment]
Resolved, and merged.
