### ISSUE TITLE
NECB2015 E+ msg: Hospital - adjacent zones with different mutipliers sharing a common surface

### ISSUE THREAD

**Issue by edwardv720** [canmet-energy/btap_tasks#92]
These surfaces are inter-zone surfaces and belong to different zones (adjacent zones). But these adjacent zones have different multipliers. This might be related to the enclosure of some zones #91. Should complete #91 before tackling this issue. 

Multiple warnings for multiple pairs of surfaces

   ENERGYPLUS ERROR MESSAGE:
   ** Warning ** GetSurfaceData: InterZone Surface Areas do not match as expected and might not satisfy conservation of energy:
   **   ~~~   **   Area=19.5, Multipliers=1, Total Area=19.5 in Surface=CORRIDOR_FLR_1-4 Zone=SP-CORRIDOR_FLR_1 SYS-3 FLR-2 SCH-B HPLCMT-NORTH ZN
   **   ~~~   **   Area=19.5, Multipliers=4, Total Area=78.0 in Surface=ER_TRIAGE_MULT4_FLR_1-1 Zone=SP-ER_TRIAGE_MULT4_FLR_1 SYS-3 FLR-2 SCH-H HPLCMT-NORTH ZN

**Comment by padmassun** [comment]
Boundary condition of surfaces with multipliers was changed to adiabatic, and resolves this issue.

Related to https://github.com/canmet-energy/btap_tasks/issues/107
