### ISSUE TITLE
NECB2015 E+ msg: Nominal pumping power is sized to 0W

### ISSUE THREAD

**Issue by edwardv720** [canmet-energy/btap_tasks#93]
- The nominal power of a constant speed pump calculated is approximately 0 W. The issue seems to be the low design pump head (0.001 Pa).
-  This error might have showed up in necb2011 archetypes

	Buildings: Retail standalone, Small Office, retail strip mall, Warehouse, quick service restaurant 
	
	
	ENERGYPLUS ERROR MESSAGE:
   ** Warning ** Check input. Pump nominal power or motor efficiency is set to 0, for pump=SERVICE WATER LOOP PUMP

**Comment by ckirney** [comment]
Reviewed affected building models since modification to shw btap modeling (issue #46).  The issue no longer appears.  Likely caused because the pump head in the affected buildings was set to close to zero.  Pump head is now set to a minimum of 1 Pa.
