### ISSUE TITLE
Implement lighting_per_area qaqc for 2015

### ISSUE THREAD

**Issue by padmassun** [canmet-energy/btap_tasks#96]
Currently QAQC for `lighting_per_area` is being skipped but to the logic changes and the complexity of calculating the LPD factors, because the LPD factors are dependent on a schedule.

**Comment by padmassun** [comment]
https://github.com/canmet-energy/btap_tasks/issues/83

**Comment by IainMacdonald** [comment]
@phylroy we think this that this can be closed as the qc check for the test in standards is sufficient.
