### ISSUE TITLE
Correctly apply the LPD ratio for NECB QAQC

### ISSUE THREAD

**Issue by padmassun** [canmet-energy/btap_tasks#97]
Currently the LPD ratios are not being applied at all for NECB qaqc.

**Comment by padmassun** [comment]
Due to the LPD ratios not being applied properly, `Outpatient`, `PrimarySchool`, `SecondarySchool`, and `SmallHotel` fails.

https://github.com/NREL/openstudio-standards/blob/892293bc2c2e8c0460e4324eece07a103d1f76cb/lib/openstudio-standards/standards/necb/necb_2011/qaqc/necb_qaqc.rb#L935

**Comment by padmassun** [comment]
Merged, but the qaqc json file must be fixed

**Comment by padmassun** [comment]
I should change the LPD ratios for other spacetypes that do not contain the `occsens`

**Comment by padmassun** [comment]
The LPD ratio for NECB 2011 for the following spacetypes should be set to 0.9
```ruby
reduce_lpd_spaces = ['Classroom/lecture/training', 'Conf./meet./multi-purpose', 'Lounge/recreation',
             'Conf./meet./multi-purpose', 'Washroom-sch-A', 'Washroom-sch-B', 'Washroom-sch-C', 'Washroom-sch-D',
             'Washroom-sch-E', 'Washroom-sch-F', 'Washroom-sch-G', 'Washroom-sch-H', 'Washroom-sch-I',
             'Dress./fitt. - performance arts', 'Locker room', 'Locker room-sch-A', 'Locker room-sch-B',
             'Locker room-sch-C', 'Locker room-sch-D', 'Locker room-sch-E', 'Locker room-sch-F', 'Locker room-sch-G',
             'Locker room-sch-H', 'Locker room-sch-I', 'Retail - dressing/fitting']
```

**Comment by padmassun** [comment]
Approach: Convert the json file into a xlsx file using [this script](https://github.com/NREL/openstudio-standards/blob/48ca9c37e1f7d6edccab840b7a670c659ec5a545/lib/openstudio-standards/standards/necb/NECB2011/data/standards_data.rb#L60). Then modify the xlsx and then convert it back to json using [this script](https://github.com/NREL/openstudio-standards/blob/48ca9c37e1f7d6edccab840b7a670c659ec5a545/lib/openstudio-standards/standards/necb/NECB2011/data/standards_data.rb#L85).

**Comment by phylroy** [comment]
This issue was corrected by jeff's implemenation and Edwards work
